name: Update Dependency

on:
  push:
    branches:
      - main 

jobs:
  update_dependency:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Get changed version
        id: get_version
        run: |
          CHANGED_VERSION=$(git show HEAD:package.json | jq -r '.version')
          echo "::set-output name=version::$CHANGED_VERSION"
          
      - name: Run updateDependency script
        run: |
          CHANGED_VERSION=${{ steps.get_version.outputs.version }}
          if [ ! -z "$CHANGED_VERSION" ]; then
            node .github/workflows/script.js "$CHANGED_VERSION"
          fi
