name: Update Dependency

on:
  push:
    branches:
      - main 

jobs:
  update_dependency:
    runs-on: ubuntu-latest
    
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Run updateDependency script
        run: |
          git diff $(git rev-list --max-parents=0 HEAD) -- package.json > package-changes.diff

          CHANGED_VERSION=$(grep -o -m 1 '"version": ".*"' package-changes.diff | grep -o '".*"' | sed 's/"//g')

          if [ ! -z "$CHANGED_VERSION" ]; then
            node .github/workflows/updateDependencyScript.js "$CHANGED_VERSION"
          fi
